baseURL = "https://healthcareisbullshit.com/"
languageCode = "The language code for the language the website is written in"
title = "Healthcare is Bullshit"
theme = "aether"
googleAnalytics = "UA-142513038-1"
disqusShortname = "Your shortname for Disqus - optional"

[params]
brand = "HCIB"
description = "All the inconsistencies with the healthcare system."
homeimg = ""
bgimg = "https://cdn.discordapp.com/attachments/634117579723636776/648213676750536704/green-single-solid-color-plain-one-colour-1920x1080-c-d5f4db-f-24.png"
